// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Uis.API.Models;

#nullable disable

namespace Uis.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251210120947_Attendances")]
    partial class Attendances
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Uis.API.Models.AcademicYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("EndYear")
                        .HasColumnType("int")
                        .HasColumnName("EndYear");

                    b.Property<DateTime>("EnrollmentEndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EnrollmentEndDate");

                    b.Property<DateTime>("EnrollmentStartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EnrollmentStartDate");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsActive");

                    b.Property<int>("StartYear")
                        .HasColumnType("int")
                        .HasColumnName("StartYear");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_AcademicYear_IsActive");

                    b.HasIndex("Year")
                        .IsUnique()
                        .HasDatabaseName("IX_AcademicYear_Year_Unique");

                    b.ToTable("AcademicYears", (string)null);
                });

            modelBuilder.Entity("Uis.API.Models.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CreatedByTeacherId")
                        .HasColumnType("int")
                        .HasColumnName("CreatedByTeacherId");

                    b.Property<string>("CreatedByTeacherName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedByTeacherName");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("PublishedAt");

                    b.Property<int?>("TargetAcademicYearId")
                        .HasColumnType("int")
                        .HasColumnName("TargetAcademicYearId");

                    b.Property<int?>("TargetCourseInstanceId")
                        .HasColumnType("int")
                        .HasColumnName("TargetCourseInstanceId");

                    b.Property<int?>("TargetDepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByTeacherId")
                        .HasDatabaseName("CreatedByTeacherId");

                    b.HasIndex("TargetAcademicYearId");

                    b.HasIndex("TargetCourseInstanceId");

                    b.HasIndex("TargetDepartmentId");

                    b.ToTable("Announcements", (string)null);
                });

            modelBuilder.Entity("Uis.API.Models.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("AttendanceDate");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int")
                        .HasColumnName("EnrollmentId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceDate")
                        .HasDatabaseName("IX_Attendance_Date");

                    b.HasIndex("EnrollmentId", "AttendanceDate")
                        .IsUnique()
                        .HasDatabaseName("IX_Attendance_Enrollment_Date_Unique");

                    b.ToTable("Attendances", (string)null);
                });

            modelBuilder.Entity("Uis.API.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CreditHours")
                        .HasColumnType("int")
                        .HasColumnName("CreditHours");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("DepartmentId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Name");

                    b.Property<int?>("PrerequisiteCourseId")
                        .HasColumnType("int")
                        .HasColumnName("PrerequisiteCourseId");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Course_Code_Unique");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("IX_Course_DepartmentId");

                    b.HasIndex("PrerequisiteCourseId");

                    b.ToTable("Courses", (string)null);
                });

            modelBuilder.Entity("Uis.API.Models.CourseInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("int")
                        .HasColumnName("AcademicYearId");

                    b.Property<int>("Capacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(30)
                        .HasColumnName("Capacity");

                    b.Property<byte[]>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("ConcurrencyToken");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseId");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CurrentEnrollmentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("CurrentEnrollmentCount");

                    b.Property<int?>("Day1")
                        .HasColumnType("int")
                        .HasColumnName("Day1");

                    b.Property<int?>("Day2")
                        .HasColumnType("int")
                        .HasColumnName("Day2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("DepartmentId");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("EndTime");

                    b.Property<string>("Location")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasDefaultValue("")
                        .HasColumnName("Location");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Section");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("StartTime");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("TeacherId");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYearId")
                        .HasDatabaseName("IX_CourseInstance_AcademicYearId");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("IX_CourseInstance_CourseId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_CourseInstance_Status_Active")
                        .HasFilter("[Status] = 1");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("IX_CourseInstance_TeacherId");

                    b.HasIndex("AcademicYearId", "DepartmentId")
                        .HasDatabaseName("IX_CourseInstance_AcademicYear_Department");

                    b.HasIndex("CourseId", "Section", "AcademicYearId")
                        .IsUnique()
                        .HasDatabaseName("IX_CourseInstance_Course_Section_Year_Unique");

                    b.ToTable("CourseInstances", (string)null);
                });

            modelBuilder.Entity("Uis.API.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Department_Code_Unique");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Department_Name");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("Uis.API.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("int")
                        .HasColumnName("AcademicYearId");

                    b.Property<int>("CourseInstanceId")
                        .HasColumnType("int")
                        .HasColumnName("CourseInstanceId");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DroppedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DroppedAt");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("EnrolledAt");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentId");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYearId")
                        .HasDatabaseName("IX_Enrollment_AcademicYearId");

                    b.HasIndex("CourseInstanceId", "Status")
                        .HasDatabaseName("IX_Enrollment_CourseInstance_Status");

                    b.HasIndex("StudentId", "Status")
                        .HasDatabaseName("IX_Enrollment_Student_Status");

                    b.HasIndex("StudentId", "CourseInstanceId", "AcademicYearId")
                        .IsUnique()
                        .HasDatabaseName("IX_Enrollment_Student_Course_Year_Unique");

                    b.ToTable("Enrollments", (string)null);
                });

            modelBuilder.Entity("Uis.API.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AcademicYearId")
                        .HasColumnType("int");

                    b.Property<int>("CourseInstanceId")
                        .HasColumnType("int")
                        .HasColumnName("CourseInstanceId");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("Exam1")
                        .HasColumnType("int");

                    b.Property<int?>("Exam2")
                        .HasColumnType("int");

                    b.Property<int?>("Final")
                        .HasColumnType("int");

                    b.Property<string>("LetterGrade")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("LetterGrade");

                    b.Property<string>("Notes")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasDefaultValue("")
                        .HasColumnName("Notes");

                    b.Property<int?>("Project")
                        .HasColumnType("int");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("Score");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentId");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("SubmittedAt");

                    b.Property<int>("SubmittedByTeacherId")
                        .HasColumnType("int")
                        .HasColumnName("SubmittedByTeacherId");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYearId");

                    b.HasIndex("CourseInstanceId", "SubmittedAt")
                        .HasDatabaseName("IX_Grade_CourseInstance_SubmittedAt");

                    b.HasIndex("StudentId", "CourseInstanceId")
                        .IsUnique()
                        .HasDatabaseName("IX_Grade_Student_Course_Unique");

                    b.HasIndex("SubmittedByTeacherId", "SubmittedAt")
                        .HasDatabaseName("IX_Grade_SubmittedBy_SubmittedAt");

                    b.ToTable("Grades", (string)null);
                });

            modelBuilder.Entity("Uis.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("FirstName");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LastName");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_User_Email_Unique");

                    b.HasIndex("Role")
                        .HasDatabaseName("IX_User_Role");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Uis.API.Models.Announcement", b =>
                {
                    b.HasOne("Uis.API.Models.User", "CreatedByTeacher")
                        .WithMany("Announcements")
                        .HasForeignKey("CreatedByTeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Uis.API.Models.AcademicYear", "TargetAcademicYear")
                        .WithMany()
                        .HasForeignKey("TargetAcademicYearId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Uis.API.Models.CourseInstance", "TargetCourseInstance")
                        .WithMany()
                        .HasForeignKey("TargetCourseInstanceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Uis.API.Models.Department", "TargetDepartment")
                        .WithMany()
                        .HasForeignKey("TargetDepartmentId");

                    b.Navigation("CreatedByTeacher");

                    b.Navigation("TargetAcademicYear");

                    b.Navigation("TargetCourseInstance");

                    b.Navigation("TargetDepartment");
                });

            modelBuilder.Entity("Uis.API.Models.Attendance", b =>
                {
                    b.HasOne("Uis.API.Models.Enrollment", "Enrollment")
                        .WithMany("Attendances")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("Uis.API.Models.Course", b =>
                {
                    b.HasOne("Uis.API.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Uis.API.Models.Course", "PrerequisiteCourse")
                        .WithMany()
                        .HasForeignKey("PrerequisiteCourseId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Department");

                    b.Navigation("PrerequisiteCourse");
                });

            modelBuilder.Entity("Uis.API.Models.CourseInstance", b =>
                {
                    b.HasOne("Uis.API.Models.AcademicYear", "AcademicYear")
                        .WithMany()
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Uis.API.Models.Course", "Course")
                        .WithMany("Instances")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Uis.API.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Uis.API.Models.User", "Teacher")
                        .WithMany("TaughtCourses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademicYear");

                    b.Navigation("Course");

                    b.Navigation("Department");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Uis.API.Models.Enrollment", b =>
                {
                    b.HasOne("Uis.API.Models.AcademicYear", "AcademicYear")
                        .WithMany()
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Uis.API.Models.CourseInstance", "CourseInstance")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Uis.API.Models.User", "Student")
                        .WithMany("StudentEnrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicYear");

                    b.Navigation("CourseInstance");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Uis.API.Models.Grade", b =>
                {
                    b.HasOne("Uis.API.Models.AcademicYear", "AcademicYear")
                        .WithMany()
                        .HasForeignKey("AcademicYearId");

                    b.HasOne("Uis.API.Models.CourseInstance", "CourseInstance")
                        .WithMany("Grades")
                        .HasForeignKey("CourseInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Uis.API.Models.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Uis.API.Models.User", "SubmittedByTeacher")
                        .WithMany("GradesSubmitted")
                        .HasForeignKey("SubmittedByTeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademicYear");

                    b.Navigation("CourseInstance");

                    b.Navigation("Student");

                    b.Navigation("SubmittedByTeacher");
                });

            modelBuilder.Entity("Uis.API.Models.User", b =>
                {
                    b.HasOne("Uis.API.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Uis.API.Models.Course", b =>
                {
                    b.Navigation("Instances");
                });

            modelBuilder.Entity("Uis.API.Models.CourseInstance", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Grades");
                });

            modelBuilder.Entity("Uis.API.Models.Department", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("Uis.API.Models.Enrollment", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("Uis.API.Models.User", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("GradesSubmitted");

                    b.Navigation("StudentEnrollments");

                    b.Navigation("TaughtCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
